config/routes.rb
Lineup3::Application.routes.draw do

root 'pages#home'
resources :barbers do
	resources :pictures
end


resources :customers do
	resources :pictures
end

resources :haircuts

resources :sessions, only: [:new, :create, :destroy]
get 'pages/landing' => 'pages#landing'
# mount FullcalendarEngine::Engine => "/fullcalendar_engine"




end

app/models/customer.rb
class Customer < ActiveRecord::Base

	has_many :haircuts
	has_many :barbers, through: :haircuts 
	has_many :pictures
	  #user profile picture upload using paperclip gem
	has_attached_file :avatar, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	  #allows users to have multiple pictures
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }

	#validations
	validates_attachment :avatar, presence: true, content_type: { content_type: ["image/jpeg", "image/jpg", "image/gif", "image/png"] }
	# validates_attachment :picture, presence: true, content_type: { content_type: ["image/jpeg", "image/jpg", "image/gif", "image/png"] }

	has_secure_password 
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def index 
	end


	def new
		@customers = Customer.new
	end

	def create 
		@customer = Customer.new(customer_params)
		if @customer.save
			session[:customer_id] = @customer_id.to_s
			redirect_to new_session_path
		else
			redirect_to new_customer_path
		end
	end

	def show
		@customer = Customer.find(params[:id])
		@barbers = Barber.all
		@barbers = Barber.where(params[:zipcode])
		# @pictures = Picture.all

		# users = User.where(name: 'David', occupation: 'Code Artist').order('created_at DESC')
	end

	def edit
		@customer = Customer.find(params[:id])
		# @picture = @customer.pictures.find(params[:id])
	end

	def update
		# @picture = @customer.picture.find(params[:id])
    	@customer = Customer.find(params[:id])
    	if @customer.update_attributes(customer_params)
      	redirect_to customers_path
    	else
        render 'edit'
    	end
    end

	 def customer_params
	    params.require(:customer).permit(:first_name, :last_name, :email, :avatar, :picture, :password, :password_confirmation, :customertype)
	 end


end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div id="edit_form">
	<div class="edit col-sm-4 center-block">

		<%= form_for @customer do |f| %>
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
				<%= f.text_field :first_name, placeholder: "What's your first name?", :class => "form-control" %>
				<%= f.text_field :last_name, placeholder: "Last name?", :class => "form-control" %>
			</div>

			<div class="input-group">
				<div class="input-group-addon" id="at-symbol-glyph">@</div>
				<%= f.email_field :email, placeholder: "Enter email", :class => "form-control" %><br />
			</div>

			<div class="input-group">
				<div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
				<%= f.password_field :password, placeholder: "Password", :class => "form-control" %>
			</div>

			<div class="input-group">
			
				<%= label_tag "Change your profile picture" %>
				<%= f.file_field :avatar %>
			</div>
		</div>
		<%= f.submit "Update", class: 'btn btn-primary btn lg btn-block'%>
		<% end %>


	</div> <!-- end of edit form -->
</div> <!-- end of columns -->


	
		

<!-- <button type="button" class="btn btn-primary btn-lg btn-block">
class: 'btn btn-large btn-primary' -->

app/views/customers/new.html.erb
<h1>Ready to Get Fresh?</h1><br>

<div class="col-sm-4 col-sm-offset-4">
<%= form_for @customers do |f| %>

	<div class="form-group">
	<%= f.text_field :email, placeholder: "E-mail", class: 'form-control' %><br />
	</div>
	
	<div class="form-group">
	<%= f.text_field :first_name, placeholder: "First Name", class: 'form-control' %><br />
	</div>

	<div class="form-group">
	<%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control' %><br />
	</div>

	<div class="form-group">
	<%= f.text_field :sex, placeholder: "Sex", class: 'form-control' %><br />
	</div>

	<div class="form-group">
	<%= f.text_field :address, placeholder: "Address", class: 'form-control' %><br />
    </div> 
    
	<div class="form-group">
	<%= f.text_field :zipcode, placeholder: "Zip Code", class: 'form-control' %><br />
	</div>
	<%= f.hidden_field :customertype, value: "Customer", class: 'form-control' %><br />
	<div class="form-group">
	<%= f.password_field :password, placeholder: "Password", class: 'form-control' %><br />
	</div>

	<div class="form-group">
	<%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form-control' %><br />
	</div>

	<%= label_tag "Upload a profile picture" %>
	<%= f.file_field :avatar %> <br>

	
	<%= f.submit "Submit", class: 'btn btn-primary'%>

	<% end %>

</div> 

app/views/customers/show.html.erb
<div id="container">



<div class="content"> <!-- This is the red background -->
		<div class="container">
			<div class="box">
				<div class="row">
				<div class="col-lg-3">
					<%= image_tag @customer.avatar.url(:large), 
					class: 'img-square img-profile', width: 267 %>
				</div>
				<div class="col-lg-5">
					<div id="greeting">
						<h1>Hi <%= @customer.first_name %>! 
							Ready for a haircut?
						</h1>
					</div>
				</div>
				<div class="col-lg-5">
					<div class="bio">
					</div>
				</div>
				</div> <!-- row -->
			</div> <!-- strip w/ hi, picture and bio -->
		</div> <!-- container -->
		<div class="container">
			<div class="endorsements">
				<div class="row">
				<%= link_to "Upload Endorsement Picture", new_barber_picture_path class: 'btn btn-primary' %>
				</div> <!-- end of 1st row of pictures -->
			</div> <!-- end of endorsements -->
		</div> <!-- end of container holding endorsements -->


</div> <!-- content div -->

 <div class="barber_search">
 	<div id="prefetch">
  	<input class="typeahead" type="text" placeholder="Barbers">
	</div>

	<div id="remote" style="text-align:center; margin-top: 50px;">
    <input class="typeahead" type="text" placeholder="Find a Barber in your zipcode">
	</div>
	<h2> All barbers in my zipcode </h2>
	<% @barbers.each do |b| %>
	<li>
	<strong> Hi!<%= @customer.first_name %> 
	Get a haircut from <%= b.first_name %> 
	</strong> 
	<%= link_to "Show me more about #{b.first_name}!", barber_path(b) %>
	</li>
	<% end %>
</div>

</div> <!-- container div -->