config/routes.rb
Lineup3::Application.routes.draw do

root 'pages#home'
resources :barbers do
	resources :pictures
end


resources :customers do
	resources :pictures
end

resources :haircuts

resources :sessions, only: [:new, :create, :destroy]
get 'pages/landing' => 'pages#landing'
# mount FullcalendarEngine::Engine => "/fullcalendar_engine"




end

app/views/layouts/_nav.html.erb
<div class="navbar transparent navbar-inverse">
<nav class="navbar navbar-default" role="navigation"> 
  <div class="container-fluid">
    
    <div class="navbar-header">
      
      <div class ="brand">
      <a class="navbar-brand" style="color: white;" href="http://localhost:3000"> Menu </a>
    </div>
  </div>

  <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
      <li class ="logout"><%= link_to "Logout", session_path, method: :delete, html:{style:"color: white;"} %></li>
    <% else %>
      <li class ="login"><a href="http://localhost:3000/session/new" style="color: white;">Login</a></li>
      <li class="dropdown">
<!--         <a href="<%= new_customer_path %>" style ="color: black;"> Sign Up </a> -->
        
      </li>
    <% end %>
  </ul>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html ng-app="lineupApp"> 
<head>
  <meta charset="utf-8">
  <title>Lineup3</title>

	 

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%#= javascript_include_tag "angular" %>
  <!-- <link rel='stylesheet' href='fullcalendar/fullcalendar.css' /> -->
<!-- <script src='fullCalendar.js'></script> -->
<!-- <script src='jquery.min.js'></script> -->

 
 
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |key, value| %>
		<div class="alert-success alert-dismissible">
			<%= value %>
		</div>
	<% end %>

<!-- <div id='calendar'></div> -->


<%= yield %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>



<!-- <script src='lib/moment.min.js'></script> -->
<!-- <script src='fullcalendar/fullcalendar.js'></script> -->
<script>
// $(document).ready(function() {
  $('#calendar').fullCalendar({
  	header: {
  		left: 'prev,next today',
  		center: 'title',
  		right: 'month,agendaWeek,agendaDay'
  	},
  	allDay: false,
  	timezone: 'UTC',
  	editable: true,
  	selectable: true,
  	events: '/haircuts.json',
  	type: "GET",
  	error: function() {
  		alert("Calendar data encountered an error");
  	}
  });

//This script is for the typeahead to work!
// $(function() {
// $("#typeahead").typeahead({
// 	source: function(query, process) {
// 		$.ajax({
// 			url: 'barbers.json', 
// 			type: 'POST', 
// 			data: 'query=' + query, 
// 			dataType: 'JSON', 
// 			async: true,
// 			success: function(data) {
// 				console.log(data);
// 				}
// 			});
// 		}
// 	});
// });

var barbers = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('zipcode'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  limit: 10,
  // limit is the number of entries that gets outputted
  prefetch: {
    // url points to a json file that contains an array of country names, see
    // https://github.com/twitter/typeahead.js/blob/gh-pages/data/countries.json
    url: '/barbers.json',
    // filter: filterResponse, 
    prefetch: true, 
    // the json file contains an array of strings, but the Bloodhound
    // suggestion engine expects JavaScript objects so this converts all of
    // those strings
    filter: function(list) {
		console.log(list);
      return $.map(list, function(barber) { return { zipcode: barber }; });
    }
  }
});


// kicks off the loading/processing of `local` and `prefetch`
barbers.initialize();
 
// passing in `null` for the `options` arguments will result in the default
// options being used
$('#prefetch .typeahead').typeahead(null, {
  name: 'barbers',
  displayKey: 'zipcode',
  // `ttAdapter` wraps the suggestion engine in an adapter that
  // is compatible with the typeahead jQuery plugin
  source: barbers.ttAdapter()
});


// This is called a prefetch which loads data from a JSON file
// $('input').typeahead({
// name: 'States',
// prefetch: '/barbers.json'
// });
</script>
	

</body>
</html>